[package]
name = "streaming-http-parser"
version = "0.1.0"
authors = ["Nikita Baksalyar <nikita.baksalyar@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.1.7"

[build-dependencies]
gcc = "0.3.5"
